name: Publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish webpage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'lkeegan'
          reponame: 'vue-template'
          token: ${{ secrets.GITHUB_TOKEN }}
